server:
  port: 5002
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    instance:
      prefer-ip-address: true
      hostname: localhost
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:5001/eureka/}
logging:
  level:
    org.spring.framework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG